[build]
  functions = "netlify/functions"
  publish = "."
[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/goals/*"
  to = "/goals/:splat"
  status = 200

[[redirects]]
  from = "/oauth/callback"
  to = "/oauth/callback.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/ArtFinalWebGL/Build/*.gz"
  [headers.values]
    Content-Encoding = "gzip"
    Cache-Control = "public, max-age=31536000"
    Content-Type = "application/octet-stream"